"""Event codes and messages for AMT alarm protocol (Contact ID)."""

# Command codes
AMT_COMMAND_CODE_CONECTAR = 0x94
AMT_COMMAND_CODE_HEARTBEAT = 0xF7
AMT_COMMAND_CODE_CONECTA_E_COMPLEMENTAR = 0x95
AMT_COMMAND_CODE_EVENT_CONTACT_ID = 0xB0
AMT_COMMAND_CODE_EVENT_DATA_HORA = 0xB4
AMT_COMMAND_CODE_EVENT_FOTO_ASSOCIADA = 0xB5
AMT_COMMAND_CODE_SOLICITA_DATA_HORA = 0x80

# Request codes
AMT_REQ_CODE_VERSAO_FIRMWARE = 0xC0
AMT_REQ_CODE_MODELO = 0xC2
AMT_REQ_CODE_MAC = 0xC4
AMT_REQ_CODE_IMEI = 0xC5
AMT_REQ_CODE_ICCD_CHIP = 0xC6
AMT_REQ_CODE_NIVEL_SINAL_GPRS3G4G = 0xD1
AMT_REQ_CODE_PRESENCA_MODULO_GPRS3G4G = 0xD3

# Protocol identifiers
AMT_PROTOCOL_ISEC_MOBILE = 0xE9
AMT_PROTOCOL_ISECPROGRAM = 0xE7

# ISECMobile response codes
AMT_ISEC_MOBILE_COMMAND_CODE_COMAND_ACCEPTED = 0xFE
AMT_ISEC_MOBILE_COMMAND_CODE_INVALID_PASSWORD = 0xE1
AMT_ISEC_MOBILE_COMMAND_CODE_INVALID_COMMAND = 0xE2
AMT_ISEC_MOBILE_COMMAND_CODE_NOT_PARTITIONED = 0xE3
AMT_ISEC_MOBILE_COMMAND_CODE_OPEN_ZONES = 0xE4
AMT_ISEC_MOBILE_COMMAND_CODE_DEPRECATED_COMMAND = 0xE5
AMT_ISEC_MOBILE_COMMAND_CODE_NO_PERMISSION_BY_PASS = 0xE6
AMT_ISEC_MOBILE_COMMAND_CODE_NO_PERMISSION = 0xE7
AMT_ISEC_MOBILE_COMMAND_CODE_ARMED = 0xE8
AMT_ISEC_MOBILE_COMMAND_CODE_NO_ZONES = 0xEA

# ISECMobile error messages (for logging)
ISEC_MOBILE_ERROR_MESSAGES = {
    AMT_ISEC_MOBILE_COMMAND_CODE_INVALID_PASSWORD: "Wrong password in AMT integration",
    AMT_ISEC_MOBILE_COMMAND_CODE_INVALID_COMMAND: "Invalid command",
    AMT_ISEC_MOBILE_COMMAND_CODE_NOT_PARTITIONED: "Not partitioned",
    AMT_ISEC_MOBILE_COMMAND_CODE_OPEN_ZONES: "Open zones",
    AMT_ISEC_MOBILE_COMMAND_CODE_DEPRECATED_COMMAND: "Deprecated command",
    AMT_ISEC_MOBILE_COMMAND_CODE_NO_PERMISSION_BY_PASS: "No permission to bypass",
    AMT_ISEC_MOBILE_COMMAND_CODE_NO_PERMISSION: "No permission for this command",
    AMT_ISEC_MOBILE_COMMAND_CODE_ARMED: "Already armed",
    AMT_ISEC_MOBILE_COMMAND_CODE_NO_ZONES: "No zones configured",
}

# Contact ID event codes
AMT_EVENT_CODE_EMERGENCIA_MEDICA = 1100
AMT_EVENT_CODE_DISPARO_OU_PANICO_DE_INCENDIO = 1110
AMT_EVENT_CODE_PANICO_AUDIVEL_OU_SILENCIOSO = 1120
AMT_EVENT_CODE_SENHA_DE_COACAO = 1121
AMT_EVENT_CODE_PANICO_SILENCIOSO = 1122
AMT_EVENT_CODE_DISPARO_DE_ZONA = 1130
AMT_EVENT_CODE_DISPARO_DE_CERCA_ELETRICA = 1131
AMT_EVENT_CODE_DISPARO_DE_ZONA_24H = 1133
AMT_EVENT_CODE_TAMPER_DO_TECLADO = 1145
AMT_EVENT_CODE_DISPARO_SILENCIOSO = 1146
AMT_EVENT_CODE_FALHA_DA_SUPERVISAO_SMART = 1147
AMT_EVENT_CODE_SOBRECARGA_NA_SAIDA_AUXILIAR = 1300
AMT_EVENT_CODE_FALHA_NA_REDE_ELETRICA = 1301
AMT_EVENT_CODE_BATERIA_PRINCIPAL_BAIXA_OU_EM_CURTO_CIRCUITO = 1302
AMT_EVENT_CODE_RESET_PELO_MODO_DE_PROGRAMACAO = 1305
AMT_EVENT_CODE_ALTERACAO_DA_PROGRAMACAO_DO_PAINEL = 1306
AMT_EVENT_CODE_BATERIA_PRINCIPAL_AUSENTE_OU_INVERTIDA = 1311
AMT_EVENT_CODE_CORTE_OU_CURTO_CIRCUITO_NA_SIRENE = 1321
AMT_EVENT_CODE_TOQUE_DE_PORTEIRO = 1322
AMT_EVENT_CODE_PROBLEMA_EM_TECLADO_OU_RECEPTOR = 1333
AMT_EVENT_CODE_FALHA_NA_LINHA_TELEFONICA = 1351
AMT_EVENT_CODE_FALHA_AO_COMUNICAR_EVENTO = 1354
AMT_EVENT_CODE_CORTE_DA_FIACAO_DOS_SENSORES = 1371
AMT_EVENT_CODE_CURTO_CIRCUITO_NA_FIACAO_DOS_SENSORES = 1372
AMT_EVENT_CODE_TAMPER_DO_SENSOR = 1383
AMT_EVENT_CODE_BATERIA_BAIXA_DE_SENSOR_SEM_FIO = 1384
AMT_EVENT_CODE_DESATIVACAO_PELO_USUARIO = 1401
AMT_EVENT_CODE_AUTO_DESATIVACAO = 1403
AMT_EVENT_CODE_DESATIVACAO_VIA_COMPUTADOR_OU_TELEFONE = 1407
AMT_EVENT_CODE_ACESSO_REMOTO_PELO_SOFTWARE_DE_DOWNLOAD_UPLOAD = 1410
AMT_EVENT_CODE_FALHA_NO_DOWNLOAD = 1413
AMT_EVENT_CODE_ACIONAMENTO_DE_PGM = 1422
AMT_EVENT_CODE_SENHA_INCORRETA = 1461
AMT_EVENT_CODE_ANULACAO_TEMPORARIA_DE_ZONA = 1570
AMT_EVENT_CODE_ANULACAO_POR_DISPARO = 1573
AMT_EVENT_CODE_TESTE_MANUAL = 1601
AMT_EVENT_CODE_TESTE_PERIODICO = 1602
AMT_EVENT_CODE_SOLICITACAO_DE_MANUTENCAO = 1616
AMT_EVENT_CODE_RESET_DO_BUFFER_DE_EVENTOS = 1621
AMT_EVENT_CODE_LOG_DE_EVENTOS_CHEIO = 1624
AMT_EVENT_CODE_DATA_E_HORA_FORAM_REINICIADAS = 1625
AMT_EVENT_CODE_RESTAURACAO_DE_INCENDIO = 3110
AMT_EVENT_CODE_RESTAURACAO_DISPARO_DE_ZONA = 3130
AMT_EVENT_CODE_RESTAURACAO_DE_DISPARO_DE_CERCA_ELETRICA = 3131
AMT_EVENT_CODE_RESTARAUCAO_DISPARO_DE_ZONA_24H = 3133
AMT_EVENT_CODE_RESTARAUCAO_TAMPER_DO_TECLADO = 3145
AMT_EVENT_CODE_RESTARAUCAO_DISPARO_SILENCIOSO = 3146
AMT_EVENT_CODE_RESTARAUCAO_DA_SUPERVISAO_SMART = 3147
AMT_EVENT_CODE_RESTARAUCAO_SOBRECARGA_NA_SAIDA_AUXILIAR = 3300
AMT_EVENT_CODE_RESTARAUCAO_FALHA_NA_REDE_ELETRICA = 3301
AMT_EVENT_CODE_RESTARAUCAO_BAT_PRINC_BAIXA_OU_EM_CURTO_CIRCUITO = 3302
AMT_EVENT_CODE_RESTARAUCAO_BAT_PRINC_AUSENTE_OU_INVERTIDA = 3311
AMT_EVENT_CODE_RESTARAUCAO_CORTE_OU_CURTO_CIRCUITO_NA_SIRENE = 3321
AMT_EVENT_CODE_RESTARAUCAO_PROBLEMA_EM_TECLADO_OU_RECEPTOR = 3333
AMT_EVENT_CODE_RESTARAUCAO_LINHA_TELEFONICA = 3351
AMT_EVENT_CODE_RESTARAUCAO_CORTE_DA_FIACAO_DOS_SENSORES = 3371
AMT_EVENT_CODE_RESTARAUCAO_CURTO_CIRCUITO_NA_FIACAO_DOS_SENSORES = 3372
AMT_EVENT_CODE_RESTARAUCAO_TAMPER_DO_SENSOR = 3383
AMT_EVENT_CODE_RESTARAUCAO_BATERIA_BAIXA_DE_SENSOR_SEM_FIO = 3384
AMT_EVENT_CODE_ATIVACAO_PELO_USUARIO = 3401
AMT_EVENT_CODE_AUTO_ATIVACAO = 3403
AMT_EVENT_CODE_ATIVACAO_VIA_COMPUTADOR_OU_TELEFONE = 3407
AMT_EVENT_CODE_ATIVACAO_POR_UMA_TECLA = 3408
AMT_EVENT_CODE_DESACIONAMENTO_DE_PGM = 3422
AMT_EVENT_CODE_ATIVACAO_PARCIAL = 3456
AMT_EVENT_CODE_KEEP_ALIVE = -2

# Event messages (PT-BR)
AMT_EVENT_MESSAGES = {
    AMT_EVENT_CODE_EMERGENCIA_MEDICA: "Emergencia Medica",
    AMT_EVENT_CODE_DISPARO_OU_PANICO_DE_INCENDIO: "Disparo ou panico de incendio",
    AMT_EVENT_CODE_PANICO_AUDIVEL_OU_SILENCIOSO: "Panico audivel ou silencioso",
    AMT_EVENT_CODE_SENHA_DE_COACAO: "Senha de coacao",
    AMT_EVENT_CODE_PANICO_SILENCIOSO: "Panico silencioso",
    AMT_EVENT_CODE_DISPARO_DE_ZONA: "Disparo de zona",
    AMT_EVENT_CODE_DISPARO_DE_CERCA_ELETRICA: "Disparo de cerca eletrica",
    AMT_EVENT_CODE_DISPARO_DE_ZONA_24H: "Disparo de zona 24h",
    AMT_EVENT_CODE_TAMPER_DO_TECLADO: "Tamper do teclado",
    AMT_EVENT_CODE_DISPARO_SILENCIOSO: "Disparo silencioso",
    AMT_EVENT_CODE_FALHA_DA_SUPERVISAO_SMART: "Falha da supervisao Smart",
    AMT_EVENT_CODE_SOBRECARGA_NA_SAIDA_AUXILIAR: "Sobrecarga na saida auxiliary",
    AMT_EVENT_CODE_FALHA_NA_REDE_ELETRICA: "Falha na rede eletrica",
    AMT_EVENT_CODE_BATERIA_PRINCIPAL_BAIXA_OU_EM_CURTO_CIRCUITO: "Bateria principal baixa ou em curto-circuito",
    AMT_EVENT_CODE_RESET_PELO_MODO_DE_PROGRAMACAO: "Reset pelo modo de programacao",
    AMT_EVENT_CODE_ALTERACAO_DA_PROGRAMACAO_DO_PAINEL: "Alteracao da programacao do painel",
    AMT_EVENT_CODE_BATERIA_PRINCIPAL_AUSENTE_OU_INVERTIDA: "Bateria principal ausente ou invertida",
    AMT_EVENT_CODE_CORTE_OU_CURTO_CIRCUITO_NA_SIRENE: "Corte ou curto-circuito na sirene",
    AMT_EVENT_CODE_TOQUE_DE_PORTEIRO: "Toque de porteiro",
    AMT_EVENT_CODE_PROBLEMA_EM_TECLADO_OU_RECEPTOR: "Problema em teclado ou receptor",
    AMT_EVENT_CODE_FALHA_NA_LINHA_TELEFONICA: "Falha na linha telefonica",
    AMT_EVENT_CODE_FALHA_AO_COMUNICAR_EVENTO: "Falha ao comunicar evento",
    AMT_EVENT_CODE_CORTE_DA_FIACAO_DOS_SENSORES: "Corte da fiacao dos sensores",
    AMT_EVENT_CODE_CURTO_CIRCUITO_NA_FIACAO_DOS_SENSORES: "Curto-circuito na fiacao dos sensores",
    AMT_EVENT_CODE_TAMPER_DO_SENSOR: "Tamper do sensor",
    AMT_EVENT_CODE_BATERIA_BAIXA_DE_SENSOR_SEM_FIO: "Bateria baixa de sensor sem fio",
    AMT_EVENT_CODE_DESATIVACAO_PELO_USUARIO: "Desativacao pelo usuario",
    AMT_EVENT_CODE_AUTO_DESATIVACAO: "Auto-desativacao",
    AMT_EVENT_CODE_DESATIVACAO_VIA_COMPUTADOR_OU_TELEFONE: "Desativacao via computador ou telefone",
    AMT_EVENT_CODE_ACESSO_REMOTO_PELO_SOFTWARE_DE_DOWNLOAD_UPLOAD: "Acesso remoto pelo software de download/upload",
    AMT_EVENT_CODE_FALHA_NO_DOWNLOAD: "Falha no download",
    AMT_EVENT_CODE_ACIONAMENTO_DE_PGM: "Acionamento de PGM",
    AMT_EVENT_CODE_SENHA_INCORRETA: "Senha incorreta",
    AMT_EVENT_CODE_ANULACAO_TEMPORARIA_DE_ZONA: "Anulacao temporaria de zona",
    AMT_EVENT_CODE_ANULACAO_POR_DISPARO: "Anulacao por disparo",
    AMT_EVENT_CODE_TESTE_MANUAL: "Teste manual",
    AMT_EVENT_CODE_TESTE_PERIODICO: "Teste periodico",
    AMT_EVENT_CODE_SOLICITACAO_DE_MANUTENCAO: "Solicitacao de manutencao",
    AMT_EVENT_CODE_RESET_DO_BUFFER_DE_EVENTOS: "Reset do buffer de eventos",
    AMT_EVENT_CODE_LOG_DE_EVENTOS_CHEIO: "Log de eventos cheio",
    AMT_EVENT_CODE_DATA_E_HORA_FORAM_REINICIADAS: "Data e hora foram reiniciadas",
    AMT_EVENT_CODE_RESTAURACAO_DE_INCENDIO: "Restauracao de incendio",
    AMT_EVENT_CODE_RESTAURACAO_DISPARO_DE_ZONA: "Restauracao disparo de zona",
    AMT_EVENT_CODE_RESTAURACAO_DE_DISPARO_DE_CERCA_ELETRICA: "Restauracao de disparo de cerca eletrica",
    AMT_EVENT_CODE_RESTARAUCAO_DISPARO_DE_ZONA_24H: "Restauracao disparo de zona 24h",
    AMT_EVENT_CODE_RESTARAUCAO_TAMPER_DO_TECLADO: "Restauracao tamper do teclado",
    AMT_EVENT_CODE_RESTARAUCAO_DISPARO_SILENCIOSO: "Restauracao disparo silencioso",
    AMT_EVENT_CODE_RESTARAUCAO_DA_SUPERVISAO_SMART: "Restauracao da supervisao Smart",
    AMT_EVENT_CODE_RESTARAUCAO_SOBRECARGA_NA_SAIDA_AUXILIAR: "Restauracao sobrecarga na saida auxiliary",
    AMT_EVENT_CODE_RESTARAUCAO_FALHA_NA_REDE_ELETRICA: "Restauracao falha na rede eletrica",
    AMT_EVENT_CODE_RESTARAUCAO_BAT_PRINC_BAIXA_OU_EM_CURTO_CIRCUITO: "Restauracao bat. princ. baixa ou em curto-circuito",
    AMT_EVENT_CODE_RESTARAUCAO_BAT_PRINC_AUSENTE_OU_INVERTIDA: "Restauracao bat. princ. ausente ou invertida",
    AMT_EVENT_CODE_RESTARAUCAO_CORTE_OU_CURTO_CIRCUITO_NA_SIRENE: "Restauracao corte ou curto-circuito na sirene",
    AMT_EVENT_CODE_RESTARAUCAO_PROBLEMA_EM_TECLADO_OU_RECEPTOR: "Restauracao problema em teclado ou receptor",
    AMT_EVENT_CODE_RESTARAUCAO_LINHA_TELEFONICA: "Restauracao linha telefonica",
    AMT_EVENT_CODE_RESTARAUCAO_CORTE_DA_FIACAO_DOS_SENSORES: "Restauracao corte da fiacao dos sensores",
    AMT_EVENT_CODE_RESTARAUCAO_CURTO_CIRCUITO_NA_FIACAO_DOS_SENSORES: "Restauracao curto-circuito na fiacao dos sensores",
    AMT_EVENT_CODE_RESTARAUCAO_TAMPER_DO_SENSOR: "Restauracao tamper do sensor",
    AMT_EVENT_CODE_RESTARAUCAO_BATERIA_BAIXA_DE_SENSOR_SEM_FIO: "Restauracao bateria baixa de sensor sem fio",
    AMT_EVENT_CODE_ATIVACAO_PELO_USUARIO: "Ativacao pelo usuario",
    AMT_EVENT_CODE_AUTO_ATIVACAO: "Auto-ativacao",
    AMT_EVENT_CODE_ATIVACAO_VIA_COMPUTADOR_OU_TELEFONE: "Ativacao via computador ou telefone",
    AMT_EVENT_CODE_ATIVACAO_POR_UMA_TECLA: "Ativacao por uma tecla",
    AMT_EVENT_CODE_DESACIONAMENTO_DE_PGM: "Desacionamento de PGM",
    AMT_EVENT_CODE_ATIVACAO_PARCIAL: "Ativacao parcial",
    AMT_EVENT_CODE_KEEP_ALIVE: "Keep-Alive",
}

# Event code groups for state machine
DEACTIVATION_EVENTS = {
    AMT_EVENT_CODE_DESATIVACAO_PELO_USUARIO,
    AMT_EVENT_CODE_AUTO_DESATIVACAO,
    AMT_EVENT_CODE_DESATIVACAO_VIA_COMPUTADOR_OU_TELEFONE,
}

ACTIVATION_EVENTS = {
    AMT_EVENT_CODE_ATIVACAO_PELO_USUARIO,
    AMT_EVENT_CODE_AUTO_ATIVACAO,
    AMT_EVENT_CODE_ATIVACAO_VIA_COMPUTADOR_OU_TELEFONE,
    AMT_EVENT_CODE_ATIVACAO_POR_UMA_TECLA,
    AMT_EVENT_CODE_ATIVACAO_PARCIAL,
}

TRIGGER_EVENTS = {
    AMT_EVENT_CODE_EMERGENCIA_MEDICA,
    AMT_EVENT_CODE_DISPARO_OU_PANICO_DE_INCENDIO,
    AMT_EVENT_CODE_PANICO_AUDIVEL_OU_SILENCIOSO,
    AMT_EVENT_CODE_SENHA_DE_COACAO,
    AMT_EVENT_CODE_PANICO_SILENCIOSO,
    AMT_EVENT_CODE_DISPARO_DE_ZONA,
    AMT_EVENT_CODE_DISPARO_DE_CERCA_ELETRICA,
    AMT_EVENT_CODE_DISPARO_DE_ZONA_24H,
    AMT_EVENT_CODE_TAMPER_DO_TECLADO,
    AMT_EVENT_CODE_DISPARO_SILENCIOSO,
    AMT_EVENT_CODE_CORTE_OU_CURTO_CIRCUITO_NA_SIRENE,
    AMT_EVENT_CODE_PROBLEMA_EM_TECLADO_OU_RECEPTOR,
    AMT_EVENT_CODE_FALHA_NA_LINHA_TELEFONICA,
    AMT_EVENT_CODE_CORTE_DA_FIACAO_DOS_SENSORES,
    AMT_EVENT_CODE_CURTO_CIRCUITO_NA_FIACAO_DOS_SENSORES,
    AMT_EVENT_CODE_TAMPER_DO_SENSOR,
}

RESTORE_EVENTS = {
    AMT_EVENT_CODE_RESTAURACAO_DE_INCENDIO,
    AMT_EVENT_CODE_RESTAURACAO_DISPARO_DE_ZONA,
    AMT_EVENT_CODE_RESTAURACAO_DE_DISPARO_DE_CERCA_ELETRICA,
    AMT_EVENT_CODE_RESTARAUCAO_DISPARO_DE_ZONA_24H,
    AMT_EVENT_CODE_RESTARAUCAO_TAMPER_DO_TECLADO,
    AMT_EVENT_CODE_RESTARAUCAO_DISPARO_SILENCIOSO,
    AMT_EVENT_CODE_RESTARAUCAO_DA_SUPERVISAO_SMART,
    AMT_EVENT_CODE_RESTARAUCAO_SOBRECARGA_NA_SAIDA_AUXILIAR,
    AMT_EVENT_CODE_RESTARAUCAO_FALHA_NA_REDE_ELETRICA,
    AMT_EVENT_CODE_RESTARAUCAO_BAT_PRINC_BAIXA_OU_EM_CURTO_CIRCUITO,
    AMT_EVENT_CODE_RESTARAUCAO_BAT_PRINC_AUSENTE_OU_INVERTIDA,
    AMT_EVENT_CODE_RESTARAUCAO_CORTE_OU_CURTO_CIRCUITO_NA_SIRENE,
    AMT_EVENT_CODE_RESTARAUCAO_PROBLEMA_EM_TECLADO_OU_RECEPTOR,
    AMT_EVENT_CODE_RESTARAUCAO_LINHA_TELEFONICA,
    AMT_EVENT_CODE_RESTARAUCAO_CORTE_DA_FIACAO_DOS_SENSORES,
    AMT_EVENT_CODE_RESTARAUCAO_CURTO_CIRCUITO_NA_FIACAO_DOS_SENSORES,
    AMT_EVENT_CODE_RESTARAUCAO_TAMPER_DO_SENSOR,
    AMT_EVENT_CODE_RESTARAUCAO_BATERIA_BAIXA_DE_SENSOR_SEM_FIO,
}
